config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'

  resources :blogs do
    resources :replies
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :replies
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :show, :destroy]

  def index
    @blog = Blog.order("created_at desc")
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(params_blog)

    if @blog.save
      redirect_to :blogs
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @blog.update(params_blog)
      redirect_to :blogs
    else
      render :new
    end
  end

  def destroy
  @blog.destroy
  redirect_to :blogs
  end

  def show
    @replies = @blog.replies
  end

  private
    def params_blog
      params.require(:blog).permit(:title, :content)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_blog, only: [:new, :create]

  def new
    @reply = @blog.replies.new
  end

  def create
    @reply = @blog.replies.new(params_reply)

    if @reply.save
      redirect_to blog_path(@blog)
    else
      render :new
    end
  end

  private
  def params_reply
    params.require(:reply).permit(:reply)
  end

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/edit.html.erb
編輯

<%= form_for @blog do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content %>
    </div>
    <%= f.submit "確定" %>
<% end %>

app/views/blogs/index.html.erb
blog's here

<%= link_to '新增', new_blog_path %>

<table>
    <thead>
        <tr>
            <th>標題</th>
            <th>內容</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        <% @blog.each do |blog| %>
            <tr>
                <td>
                    <%= link_to blog_path(blog) do %>
                        <%= blog.title %>
                    <% end %>
                </td>
                <td>
                    <%= blog.content %>
                </td>
                <td>
                    <%= link_to "編輯", edit_blog_path(blog) %>
                    <%= link_to "刪除", blog_path(blog), method: :delete, data: { confirm: "sure?" } %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/blogs/new.html.erb
<%= form_for @blog do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content %>
    </div>

    <%= f.submit "確定" %>
<% end %>

<%= link_to "回首頁", "/" %>

app/views/blogs/show.html.erb
標題：
<%= @blog.title %>

<br>

內容：
<%= @blog.content %>

<br>

<%= link_to "返回", blogs_path %>

<br>

<%= link_to "新增留言", new_blog_reply_path(@blog) %>

<table>
    <thead>
        <tr>
            <th>留言</th>
        </tr>
    </thead>
    <tbody>
        <% @replies.each do |reply| %>
            <tr>
                <td><%= reply.reply %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/replies/new.html.erb
<%= form_for [@blog, @reply] do |f| %>
    <%= f.text_field :reply %>

    <br>

    <%= f.submit "確定" %>
<% end %>